### ISSUE TITLE
【iOS】Carthageを利用したNCMB SDK（Ver2.4.0）インストールでエラーが出る

### ISSUE THREAD

**Issue by waspossible** [NIFTYCloud-mbaas/ncmb_ios#142]
- SDKのバージョン(SDK version)  2.4.0
- 不具合が発生した環境(Environment requirement) 
　MacOSX 10.12.6　Unityでビルドしたプロジェクトにインストールを試みる
　Unityのバージョンは2017.2.0f3
- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
　CarthageでNCMBをインストールするとエラーメッセージが出る
- エラーメッセージ(Error messages) 
　Build Failed　Task failed with exit code 65:

お世話になっております。

Carthugeを利用してNCMB SDKをインストールしようとしたのですが、「Task failed with exit code 65:」というエラーが出現し、正常に終了いたしません。Ver2.3.7の時は正常にインストールが出来ました。

手順はこちらを参照しております。
http://mb.cloud.nifty.com/doc/current/introduction/quickstart_ios.html

こちらでも調査をしてみたのですが、プロジェクトディレクトリ＞Carthage＞Checkouts＞ncb_ios>NCMB.xcodeprojを開いた所、「NCMBURLConnection.h」と「NCMBURLConnection.m」のファイルが無いと出ております。フォルダもあさってみたのですが、たしかに上記のファイルはありませんでした。

<img width="287" alt="2017-10-14 4 24 12" src="https://user-images.githubusercontent.com/13376725/31563024-83a3264e-b098-11e7-9b72-99d9aa662422.png">

今回のインストールが出来ない不具合に関連性があるか分かりませんが、一応報告いたします。お忙しい所本当に恐縮ですが、何卒調査の程よろしくお願いいたします。

**Comment by ncmbsdk** [comment]
@waspossible 様
issueに起票していただき、ありがとうございます。
10/17(火) 13:30にこちらの不具合の対応をいたしました。
詳細に関してはリリースページに記載しています。
https://github.com/NIFTYCloud-mbaas/ncmb_ios/releases/tag/v2.4.0
今後も mobile backend をよろしくお願いいたします。
