### ISSUE TITLE
Facebookが提供しているiOS SDKのv4.2.0以降でFacebookアカウント連携が実施できない

### ISSUE THREAD

**Issue by ncmbsdk** [NIFTYCloud-mbaas/ncmb_ios#24]

**Comment by ncmbsdk** [comment]
v4.1.0を使用してください。

```
platform :ios, '7.0'

tartget :YourAppTarget do
    pod 'NCMB', :git =>NIFTYCloud-mbaas/ncmb_ios.git'
    pod 'FBSDKCoreKit', '~> 4.1.0'
    pod 'FBSDKLoginKit', '~> 4.1.0'
end
```

**Comment by masuhara** [comment]
@ncmbinfo 私も同じ問題に困っております。こちらは2016年3月8日現在、未対応でしょうか？FBSDKのバージョンは下げられないので未対応の場合、なるべく早い解決を宜しくお願い致します。

**Comment by ncmbsdk** [comment]
[v2.3.1](https://github.com/NIFTYCloud-mbaas/ncmb_ios/releases/tag/v2.3.1)のリリース時に動作確認したところ、
Cocoapods によりFacebook SDKを導入することで Facebook SDK v4.11.0での動作確認ができました。
