### ISSUE TITLE
iOS 9 でのsaveEventually / deleteEventuallyメソッドの不具合について

### ISSUE THREAD

**Issue by Rebirthble** [NIFTYCloud-mbaas/ncmb_ios#31]
オフラインだった場合に保存・削除処理を保留にしてオンライン時に再度実行するsaveEventually / deleteEventually メソッドについて、
iOS 9 では、オフライン時に保留にされた処理がオンライン時に2度実行されてしまう不具合があります。

オブジェクトの保存・削除はsaveInBackgroundWithBlock:やdeleteInBackgroundWithBlock:メソッドをご利用ください。

お客様にはご迷惑をおかけいたしますが、
SDKのバージョンアップまでいましばらくお待ちいただきますようお願い申し上げます。

**Comment by ncmbsdk** [comment]
v2.2.4で対応が完了したのでクローズします。
