### ISSUE TITLE
NCMBInstallationのaddUniqueObjectを使用した時にクラッシュする

### ISSUE THREAD

**Issue by shushutochako** [NIFTYCloud-mbaas/ncmb_ios#35]
下記のようなコードでinstallationに独自フィールドを設定しようとしたのですが、何回やっても
saveInBackgroundのところで再帰処理中にクラッシュしてしまいます。
Web画面を見ると配列情報は期待通り登録されていました。
この処理自体はsignUpInBackgroundWithBlockのコールバックで成功した時に実行しています。

```
実行コード

  class func registerPushFilter(filterName: String, value: String) {
    let currentInstallation = NCMBInstallation.currentInstallation()
    currentInstallation.addUniqueObject(value, forKey: filterName)
    currentInstallation.saveInBackgroundWithBlock{
      (error: NSError?) in
      // TODO：何か再送するしくみ
    }
  }
```

開発環境はこんな感じです。
- Xcode7.2
- Cocoapod0.39.0

![2016-02-06 15 37 57](https://cloud.githubusercontent.com/assets/8078429/12865145/f78f4cb8-cce7-11e5-91c3-16c53296a2e8.png)

呼び方などに何か問題ありますでしょうか？

**Comment by ncmbsdk** [comment]
@shushutochako 

- ニフティクラウド mobile backend iOS SDK v2.2.5
- Xcode 7.2
- Cocoapods 1.0.0 beta 2

上記の環境で弊社でも動作確認を行いましたが、
お問い合わせいただいたエラーを再現できておりません。
念のため以下の情報もご教授願えませんでしょうか。

- 使用している ニフティクラウド mobile backend iOS SDKのバージョン
- エラーが発生した端末の情報（実機 or エミュレータ、OSのバージョンなど）

**Comment by shushutochako** [comment]
@ncmbsdk 
ご返信ありがとうございます！ 環境は下記になります

- mobile backend iOS SDKバージョン
    - 2.25
- 端末情報
   - モデル：iPhone6(実機)
   - OS：iOS9.2

**Comment by ncmbsdk** [comment]
@shushutochako 

ニフティクラウド mobile backendのSDKのバージョンはv2.2.5でよろしいでしょうか。

弊社でも実機確認を行いましたが、addUniqueObjectを使った値の登録は問題なく可能でした。
お手数おかけしてしまい申し訳ありませんが、以下の情報についてもご教授願えませんでしょうか。

- 登録しようとしている配列情報のサンプル
- エラーを再現させるための手順や条件（お問い合わせいただいたコードを実行する以外に手順がある場合など）

**Comment by shushutochako** [comment]
@ncmbadmin 
ご回答ありがとうございます！

ニフティクラウド mobile backendのSDKのバージョンはv2.2.5でよろしいでしょうか。
→v2.2.5です。

登録しようとしている配列情報のサンプル
→下記のような情報を登録しようとしています
```
    currentInstallation.addUniqueObject("aaaaaaa", forKey: "userName")
```
エラーを再現させるための手順や条件（お問い合わせいただいたコードを実行する以外に手順がある場合など）
→他に発生させる手順はわかりませんので、継続して検証してみます！

**Comment by shushutochako** [comment]
@ncmbadmin 
ちなみにconvertToJSONFromNCMBObjectメソッドの下記の部分についてお聞きしたいのですが、
```
    } else if ([obj isKindOfClass:[NSSet class]]){
        NSMutableSet *currentSet = [NSMutableSet setWithObject:obj];
        NSMutableSet *set = [NSMutableSet set];
        for (id value in [currentSet objectEnumerator]){
            //objがNSSetだったら再帰呼び出し
            [set addObject:[self convertToJSONFromNCMBObject:value]];
        }
        return set;
        
    }
    //その他の型(文字列、数値、真偽値)はそのまま返却
    return obj;
```

NSSetクラスのobjで新規にNSSetの入れ子であるcurrentSetを作り、それを元に再帰処理をしているので処理がずっと繰返されるという事にはならないのでしょうか？

**Comment by ncmbsdk** [comment]
@shushutochako 
上記のNSSetが処理される部分では、無限ループになってしまうことを確認したため、SDKの修正を実施してまいります。
ご迷惑をおかけしてしまい申し訳ありません。

上記の不具合は
あるフィールドにNSDictionaryが設定されており、そのNSDictionaryの要素にNSSetが含まれていると再現いたしました。
（下記のサンプルコードはObjective-Cですが、NSSetのオブジェクトを含むNSDictionaryを設定しているコードになります。）

```
    //NSSet型を要素に持つNSMutableDictionaryを作成
    NSSet *set = [NSSet setWithObjects:@"あ", @"い", @"う", nil];
    NSMutableDictionary *mdic = [NSMutableDictionary dictionary];
    [mdic setObject:set forKey:@"NSSet"];

    //保存
    NCMBInstallation *currentInstallation = [NCMBInstallation currentInstallation];
    [currentInstallation setObject:mdic forKey:@"NSMutableDictionary"];
    [currentInstallation addUniqueObject:@"value" forKey:@"key"];
    [currentInstallation saveInBackgroundWithBlock:^(NSError *error) {
        if(error == nil){
            NSLog(@"成功");
        } else {
            NSLog(@"失敗:%@",error);
        }
    }];
```

お問い合わせいただいた状況ですと、addUniqueObjectの呼び出し時には文字列を設定されていらっしゃるようでしたので、他の部分で上記のようなデータの設定を行っていないか確認していただけませんでしょうか。

引き続きよろしくお願いいたします。

**Comment by shushutochako** [comment]
@ncmbsdk 上記不具合の対応をして頂ける旨ありがとうございます！！
再度確認しましたが、アプリ側では他にcurrentInstallationにobjectをsetするような処理は実装していません。
一点ご確認頂きたいのですがNCMBAddUniqueOperationクラスの下記処理に登録objectをNSSetで包む処理があるのですが、こちらに起因してはいないでしょうか！？
```
- (NCMBAddUniqueOperation *)initWithClassName:(id)newValue{
    self = [super init];
    if( self ) {
        self.objects =  [NSMutableSet set];
        if ([newValue isKindOfClass:[NSArray class]]) {
            NSMutableArray *newArray = (NSMutableArray *)newValue;
            [self.objects addObjectsFromArray:newArray];
        }else{
            [self.objects addObject:newValue];
        }
    }
    return self;
}
```

補足ですが、作成中のアプリではAppDelegateの実装にてinstallationにobjectを登録しています。
```
  func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
    let installation = NCMBInstallation.currentInstallation()
    installation.setDeviceTokenFromData(deviceToken)
    installation.saveInBackgroundWithBlock{
      (error: NSError?) in
      if let error = error {
        if error.code == 409001 {
          // デバイストークンの重複エラーの場合は情報を上書き
          self.updateExistInstallation(installation)
        }
      }
    }
  }
```
  
  

installationにobjectが登録済みの場合、NCMBObjectクラスの下記処理にてNCMBAddUniqueOperationでインスタンスを生成する気がするのでこの事象が発生しているのではないかと思っております。
```
    else{
        //objectIDがある場合　AddUniqueOperation(サーバーサイド処理)実行
        NCMBAddUniqueOperation *operation = [[NCMBAddUniqueOperation alloc]initWithClassName:objects];
        [self performOperation:key byOperation:operation];
    }
```

お手数ですが、ご確認お願いいたします！！

**Comment by ncmbsdk** [comment]
@shushutochako 
v2.2.6での対応が完了しました。
動作確認していいただき、問題がなければクローズしていただけますでしょうか。

**Comment by shushutochako** [comment]
@ncmbsdk 
v2.2.6で問題なく処理が完了することを確認しました。
ご対応ありがとうございます！！
