### ISSUE TITLE
Twitter認証機能で、iPadでのTwitter新規登録ができない

### ISSUE THREAD

**Issue by RSDessin** [NIFTYCloud-mbaas/ncmb_ios#46]
SNS認証機能のうち、Twitter認証機能で、一部動作が正常に行えません。

認証時、Twitterアカウント情報を入力する画面が出てきますが、
iPad版だと、画面右上のTwitter新規登録ボタンを押すことができません。
ActionSheetを使用しているためだと思われます。

**Comment by oonoyosp** [comment]
#73 で対応済み
