### ISSUE TITLE
Use of undeclared identifier 'UIDevice'

### ISSUE THREAD

**Issue by cafedeichi** [NIFTYCloud-mbaas/ncmb_ios#47]
Ver 2.3.0をPodsを介さずにダウンロードし、NMCBフォルダを既存プロジェクト（Swiftで記述）に上書きしてビルドした結果、以下のエラーが発生。新規プロジェクトでも同様。

> ...NCMB/NCBMRequest/NCMBRequest.m:76:11:Use of undeclared identifier 'UIDevice'

尚、NCMB.hにUIKit/UIKit.hを追記してビルドエラーを回避した。

参考URL
http://mb.cloud.nifty.com/doc/current/introduction/quickstart_ios.html#SDKをダウンロードして利用する

**Comment by cafedeichi** [comment]
NCMB.hファイルに手を加えない方法として
Podsで作成した時のようにPrefix HeaderファイルをつくってUIKit/UIKit.hを先にインポートするようにしました。Podsを使わない場合の手順「SDKをダウンロードして利用する」に追記しておいてください。

**Comment by ncmbsdk** [comment]
[v2.3.1](https://github.com/NIFTYCloud-mbaas/ncmb_ios/releases/tag/v2.3.1)にて、エラーを解消するPull Requestをマージしました。
