### ISSUE TITLE
Google Sign-in for iOS v3.0.0を使用する場合について

### ISSUE THREAD

**Issue by ykokw** [NIFTYCloud-mbaas/ncmb_ios#48]
Google Sign-in for iOS v3.0.0から、GIDSignInクラスのuiDelegateプロパティの設定が必須となり
アプリ内でのWebViewを使ったサインインのみ利用可能となっているため、
ニフティクラウド mobile backend への会員登録にGoogle認証を利用する場合も、
アプリ内でのWebViewを利用する方法のみ利用可能となります。

[参考:WebViewを利用する場合のニフティクラウド mobile backendへの会員登録の実装方法](http://mb.cloud.nifty.com/doc/current/sns/google_ios.html#アプリ内でWebViewを開いて認証を行いたい場合)

[参考:Google Sign-in for iOS リリースノート](https://developers.google.com/identity/sign-in/ios/release)

**Comment by ncmbsdk** [comment]
Google Sign-in for iOS v4.0.0から
`GIDSignIn`クラスの`allowsSignInWithWebView`プロパティが削除されており、
ニフティクラウド mobile backendのiOS SDKが上記プロパティを利用していることから
ビルドエラーとなる現象を確認しております。

iOS SDKの改修をすすめてまいりますが、
暫定対応としてGoogle Sign-in for iOS v3.0.0を利用することで、
アプリ内でWebviewを利用する方法でのGoogleアカウント連携が可能となっております。

お客様にはご迷惑をおかけいたしますが、
SDKのバージョンアップまでいましばらくお待ちいただきますようお願い申し上げます。

**Comment by ncmbsdk** [comment]
v2.3.3で対応済みのため、closeします
