### ISSUE TITLE
unLinkUserしても、authDataからデータが消えない

### ISSUE THREAD

**Issue by gucchi43** [NIFTYCloud-mbaas/ncmb_ios#65]
### 環境
- SDK NCMB (2.3.2) (podで入れています)
- swift, xcode7.3.1, ビルド環境(シュミレーター、実機ともに)
### 再現手順

① linkUserのメソッドでTwitterアカウントを連携する。（アプリ上のログ、管理画面側共にauthDataにデータが入っている）
② unLinkUserのメソッドでTwitterのアカウントの連携を解除する。（アプリ上のログのauthDataは消えているが、管理画面のauthDataは消えていない）
### 備考
- FacebookもTwitterと全く同じ挙動（メールアドレスはわかりません）
- authDataが実際は消えていないため、再ログイン時とかに、user情報をfetchしてきたらアンリンクしたはずの連携が残っている状態でとってきてしまうことになる
- 7/4日のハンズオンセミナーでも直接、社員さんにはお話、再現させてもらいました。改善なるはやでよろしくお願いいたします。

**Comment by oonoyosp** [comment]
#73 で対応済み
