### ISSUE TITLE
isLinkedWithUserをすると、アプリ上のauthDataが新しく連携したSNSの情報だけになってしまう

### ISSUE THREAD

**Issue by gucchi43** [NIFTYCloud-mbaas/ncmb_ios#66]
### 環境
- SDK NCMB (2.3.2) (podで入れています)
- swift, xcode7.3.1, ビルド環境(シュミレーター、実機ともに)
### 再現手順

①先にFacebook連携しており、authDataにFacebookのデータがある
②その後TwitterでlinkUserをすると、管理画面のauthDataにはFacebookとTwitterが入ってるのだが、アプリ内のログを出すとauthDataにはTwitterだけしか入っていない
③そのため、NCMBFacebookUtils.isLinkedWithUser(user)をすると、管理画面では連携できてるが、アプリ内で連携できていないため、falseが返って来る
### 備考
- TwitterとFacebookは順番が反対でも全く同じ挙動（メールアドレスはわかりません）
- 7/4日のハンズオンセミナーでも直接、社員さんにはお話させてもらいました。改善なるはやでよろしくお願いいたします。

**Comment by oonoyosp** [comment]
#73 で対応済み
