### ISSUE TITLE
オフラインで NCMBObject.saveEventually 実行時の Result Block がメインスレッドで実行されない

### ISSUE THREAD

**Issue by temoki** [NIFTYCloud-mbaas/ncmb_ios#74]
SDK version: 2.3.3

下記のとおり、 `NCMBObject.saveEventually` をオフラインで実行した場合のみ、Result Block がメインスレッドではない別のスレッド実行されるのですが仕様でしょうか？
- `NCMBObject` クラスの `saveInBackgroundWithBlock` メソッド
  - オンラインで実行時の Result Block : メインスレッド `NSError == nil`
  - オフラインで実行時の Result Block : メインスレッド `NSError != nil` (オフラインのエラー)
- `NCMBObject` クラスの `saveEventually` メソッド
  - オンラインで実行時の Result Block : メインスレッド `NSError == nil`
  - オフラインで実行時の Result Block : **別のスレッド** `NSError == nil`

**Comment by ncmbsdk** [comment]
@temoki 様

ご報告いただきました内容は仕様でございます。
本仕様に関してご利用上の不都合がある場合は、
再度コメントにてご意見を頂けますと幸いです。

以下、現在のsaveEventuallyの仕様に関する概要です。

> saveEventuallyは通信可否を判断して処理を分岐しております。
> オフライン時は、次にオンラインになった際にリクエストを再試行するために
> リクエスト内容をローカルファイルに保存する処理を別スレッドにて実行し
> 完了後にコールバックにnilを渡しております。
> このため、オンライン時とは異なるスレッドでの処理となっております。
> ※**参考**：saveEventuallyに関するドキュメント
> http://mb.cloud.nifty.com/assets/sdk_doc/ios/doc/html/Classes/NCMBObject.html#//api/name/saveEventually:
> 「saveEventually実行時にオフラインだった場合はerrorにnilが渡される」と記載がございますのでご覧ください。

そのほか、実装方法などの技術的なご質問やご相談が必要な場合は、
ユーザーコミュニティーやテクニカルサポートのご利用をご検討ください。
https://github.com/NIFTYCloud-mbaas/UserCommunity
http://mb.cloud.nifty.com/support.htm

**Comment by temoki** [comment]
@ncmbsdk ご回答ありがとうございました。
