### ISSUE TITLE
SDKのバージョンについて

### ISSUE THREAD

**Issue by kimpeng** [NIFTYCloud-mbaas/ncmb_ios#75]
古いSDKのバージョンはどこで確認できますか？古いSDKは最新にアップデートしないと使えなくなる可能性はあるでしょうか？

**Comment by ykokw** [comment]
古いSDKのバージョンは本リポジトリのreleasesから確認ができます。

v2.2.4 より古いSDKでは、IPv6に対応していない部分があったためAppleの審査時にリジェクトされる可能性があります。
[Release v2.2.4 · NIFTYCloud-mbaas/ncmb_ios](https://github.com/NIFTYCloud-mbaas/ncmb_ios/releases/tag/v2.2.4)

**Comment by kimpeng** [comment]
回答ありがとうございます。助かりました。
