### ISSUE TITLE
whereKey(_:notContainedIn:)でAmbiguouse use ofのエラー

### ISSUE THREAD

**Issue by imagepit** [NIFTYCloud-mbaas/ncmb_ios#85]
## 不具合の概要(Description of bug)

`whereKey(_:notContainedIn:)`を実行すると`Ambiguouse use of `whereKey(_:notContainedIn:)`のエラーがでます。

## 開発環境

|項目|値|
|---|---|
|SDKのバージョン(SDK version)|2.3.3|
|不具合が発生した環境|MacOS10.12、Xcode8、Swift3|

## 不具合を再現させる手順・サンプルコード

下記のとおり、`whereKey(_:notContainedIn:)`を実行しようとするとエラーが出ます。

![](https://www.evernote.com/l/AB0La2AbJORAbrOH8wFfLn9SwAHGmwY7psoB/image.png)

このエラーはこのメソッドの名前が複数の箇所で定義されていて、どちらのメソッドを示しているのかわからない場合に起きるエラーです。確かに、対象クラスのヘッダーを見ると同じ定義のメソッドが2つあるように見えます。

![](https://www.evernote.com/l/AB1qR7_scV5DB5uxKDhVXfC7lzmEzI2OrKgB/image.png)

## エラーメッセージ

```
Ambiguouse use of `whereKey(_:notContainedIn:)`
```

**Comment by masuhara** [comment]
2017年8月18日現在こちらまだ直っていないようですが、いかがでしょうか？

**Comment by imagepit** [comment]
こちらいつリリース予定になりますでしょうか？
