### ISSUE TITLE
NCMBQuery.findObjectsで１００件以上のデータが取れない

### ISSUE THREAD

**Issue by kimpeng** [NIFTYCloud-mbaas/ncmb_ios#87]
orQueryで- (void)whereKey:(NSString *)key containedIn:(NSArray *)array;この条件を追加すると、100件のデータまでしか取れません。
原因はなんでしょうか？

**Comment by ncmbsdk** [comment]
@kimpeng 様

issue登録いただき、ありがとうございます。
本件については、サービスの仕様になります。
ニフティクラウドmobile backendの仕様により、
100件を超えるデータの取得はlimitの設定が必要となります。
こちらのドキュメントをご参考ください。
http://mb.cloud.nifty.com/doc/current/rest/common/query.html#その他クエリのキーについて

不具合ではないため、本件をクローズさせていただきます。
以後ご質問などありましたら、[コミュニティ](https://github.com/NIFTYCloud-mbaas/UserCommunity)または[テクニカルサポート（有償）](http://mb.cloud.nifty.com/support.htm)をご活用ください。

このたび、貴重なフィードバックいただき、ありがとうございます。
今後とも、ニフティクラウドmobile backendよろしくお願いします。

**Comment by kimpeng** [comment]
limit設定500に設定してあります。
質問のように、orQueryで- (void)whereKey:(NSString *)key containedIn:(NSArray *)arrayで検索すると100件までしか取れない、この条件を解除して検索すると100件以上取れます。
なので、本件を再開させていただきます。
